name: Run Lizard Library Check
on: 
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  lizard:
    name: RUN Code Complexity Check
    strategy:
      matrix:
        module: [PUSHBUTTON , SWITCH]
        output: ["","./out/CCM_report.html"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create out folder
        run: mkdir out

      - name: Lizard Runner
        uses: niwciu/Lizard-Runner@main
        with:
          path: "./src/${{matrix.module}}"
          CCN: "12"
          Threshold: "nloc=30"
          language: "cpp"
          verbose: "true"
          arguments: "4"
          output_file: ${{matrix.output}}

      - name: Archive ${{matrix.module}} Code Complexity Metrix artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.module}}_CCM_report

          path: ./out
          if-no-files-found: error
          overwrite: true

        
