name: test
on:
    workflow_dispatch: 

jobs:
    generate_ccm_ccr_reports:
        name: Generate Code Coverage Report
        runs-on: ubuntu-latest
        container: 
          image: niwciu/stm32_dev_container:1.0.3
          options: --user root
        steps:
            - name: checkout
              uses: actions/checkout@v4
              
            - name: Create PyScript Venv
              working-directory: test/_config_scripts
              shell: bash
              run: |
                python3 -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
                deactivate

            - name: Run All Targets
              working-directory: test/_config_scripts/run_targets
              shell: bash
              run: |
                source ../venv/bin/activate
                python3 run_targets.py -rp
                deactivate

            - name: Save Generated Reports
              uses: actions/upload-artifact@v4
              with:
                  name: CCM_CCR_Reports
                  path: ./reports # need to save all files in folder
                  if-no-files-found: warn
                  retention-days: 5
                  overwrite: true